rootdir/fstab.tone

shell@F8131:/sys/devices/soc/74a4900.sdhci/mmc_host $ ls
mmc1

tone: fix sdhci path

---

rootdir/init.recovery.tone.rc
rootdir/init.tone.rc

shell@F8131:/sys/devices/soc/7464900.sdhci/mmc_host $ ls
mmc0

tone: fix paths for mmc0

---

rootdir/init.tone.pwr.rc

msm8996 is a quad-core SoC (CPU0 - CPU1 - CPU2 - CPU3)

tone: remove not needed CPU4 CPU5

---

Android.mk
README.md

tone: allow kagura

---

PlatformConfig.mk

7.1.1_r4 requirement
https://android.googlesource.com/platform/external/libnfc-nci/+/android-7.1.1_r4/halimpl/pn54x/Android.mk#15

[master] sony: tone: Update NFC chip type config

---

rootdir/ueventd.tone.rc

also removed not present dev paths

tone: ueventd: fix nfc permissions

---

bluetooth/bdroid_buildcfg.h

tone: bt: add kagura support

---

rootdir/ueventd.tone.rc

Change-Id: Ifd2fa30b065617cbd8e9ae1a983e418c4046b409

sony: tone: Fix led blink permissions

---

README.md

Change-Id: I76f41ea938bb7c92bc2b3a0de3e522543bff0b43

README.md: Add Xperia XZs (keyaki)

---

PlatformConfig.mk
platform.mk

move to platform.mk or it is ignored by compiler
Signed-off-by: David Viteri <Davidteri91@gmail.com>

tone: fix HAL3 prop

---

bluetooth/bdroid_buildcfg.h

tone: BT: add keyaki

---

rootdir/system/etc/audio_platform_info.xml
sepolicy_platform/file_contexts

Add audio_platform_info.xml and sepolicy permissions for dsp.
Thanks to @oshmoun !

[master] Add acdb requirements

---

rootdir/system/etc/audio_platform_info.xml

Now we can talk normally during calls.
Thanks to @oshmoun for this one.
Change-Id: Ib6b19b6a7fc853d02b3eeb0a064e5b3f4ba29e55

[master] sony: tone: Fix handset mic acdb id

---

platform.mk
rootdir/init.tone.rc
rootdir/system/etc/platform_p2p_supplicant_overlay.conf
rootdir/system/etc/platform_wpa_supplicant_overlay.conf

Fix random reboots due to unsupportable feature: "wowlan_triggers"
Thanks to @oshmoun for this one!

[master] Update wpa/p2p parameters

---

rootdir/init.tone.pwr.rc

dora:/dev/cpuctl # ls
cgroup.clone_children  cgroup.sane_behavior  cpu.rt_runtime_us  cpu.upmigrate_discourage  release_agent
cgroup.procs           cpu.rt_period_us      cpu.shares         notify_on_release         tasks

tone: fix init power paths

---

rootdir/system/etc/media_codecs.xml
rootdir/system/etc/media_codecs_performance.xml
rootdir/system/etc/media_profiles_V1_0.xml

tone: update media conf files

---

rootdir/init.tone.rc

Change-Id: I50830613c013b2ba28c3f42ebd4effbd0d714de3

[master] sony: tone: Move fstab mount process to common

---

rootdir/init.tone.rc

commonize init stuff
Change-Id: I44d2378938589d7070eb7bae047a75b87c9145af

[o-mr0] sony: tone: init: Move common stuff

---

rootdir/init.tone.rc

Move common init stuff between loire, tone and yoshino platforms.

[master] Move common init stuff

---

platform.mk
rootdir/vendor/etc/audio_platform_info.xml

Had to resave the entire file with unix line endings

Add fluence modes and update audio platform info

---

rootdir/vendor/etc/fstab.tone

Bug: 30807864
Change-Id: If3f67d5b7b15409c2717ef0d92851ca46677e4ff

Remove discard in fstab

---

rootdir/vendor/etc/fstab.tone

Bug: 38351804
Test: boot
Change-Id: Ibe884310960f88ce7dd757a50b232fc70ae89274

Add quota support to data partition

---

rootdir/vendor/etc/init/init.tone.pwr.rc

Some basic edits that should not harm anything.

Clean up init.tone.pwr.rc

---

rootdir/vendor/etc/init/init.tone.pwr.rc

the same driver same paths are used by all platforms move it to common repo

PowerHal: move all needed perm to common

---

sepolicy_platform/genfs_contexts

sepolicy: avoid sde denials

---

PlatformConfig.mk

this was reworked in fpc hal in commit ee01f1e19c3a192430d5376d8ac01e4cfd214c50

remove not needed FPC flag

---

rootdir/vendor/etc/fstab.tone

**VERIFY ME!**
Makes things neater with the stage-separated mounting logic in Q and later.

[VERIFYME] fstab: Split into early and latemount, reserve 128M on /data
