sonyxperiadev/device-sony-tone

rootdir/init.tone.rc
this can be regulated when AOSP kernel is up
fixing this for don't use wrong CPUs
=> tone: fix CPUSETS for quad-core platform

rootdir/fstab.tone
change it because there is not /config partition in msm8996 ( check with F8131 - dora )
use /frp for it
259        8        512 mmcblk0p40
=> tone: use /frp as /persistent partition

PlatformConfig.mk, platform.mk
* Avoid hardcoding the paths by using common
variables declared once for path accesses
Change-Id: I81226a249c6258360c540c80ae4dfe5073439921
Signed-off-by: Adrian DC <radian.dc@gmail.com>
=> tone: config: Use unique variables for device paths

PlatformConfig.mk
It is expected from sdhci driver@3.18.
=> [master] sony: tone: Add androidboot.bootdevice to cmdline

rootdir/init.tone.rc
Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.
tone exclusive edit by Myself5: the macaddr sysfs path is not known yet, so keep the "old lines" but the new ones commented, so once
we know the the path we can just uncomment the proper lines
Signed-off-by: Adam Farden adam@farden.cz
=> macaddr: remove dangerous sepolicy permissions

PlatformConfig.mk
following marlin config https://android.googlesource.com/device/google/marlin/+/android-7.1.1_r8/marlin/BoardConfig.mk#200
=> tone: use correct flag nfc for android-7.1.1

system.prop
The rqbalance parameters in this file were copied from another device
while early porting: this was wrong (and pretty normal, for that time).
Tune the parameters for a good balance between performance and
battery saving.
=> system.prop: Tune rqbalance parameters for MSM8996

bluetooth/bdroid_buildcfg.h, rootdir/system/etc/bluetooth/bt_vendor.conf
- UartPort is evaluated by libbt (pass BT data to the brcm ldisc driver).
UimUartPort is evaluated by the uim service which needs to be aware of
the uart device node to which the ldisc driver is attached.
Naming aligned with Ie185dcc8aa965b2d4df7dea26adbcc1036c38c6a
- Disable power state handling by libbt as it is done in the brcm driver.
Change-Id: Ifddbc4e3867a62f821a0081312ec441fbe390c49
Signed-off-by: Alexander Diewald <Diewi@diewald-net.com>
=> Adjust device nodes for the brcm BT/FMRadio driver & power handling

bluetooth/bdroid_buildcfg.h
this is not needed after a28d33aa570941e79f0037c1df4f9995ef6e0591
=> tone: bt: cleanup

rootdir/init.tone.pwr.rc
For CPU bandwidth management this allows for better power saving,
since the default governor was "performance", keeping the bus always
at a high frequency.
About memory bus latency control, by default it uses the "powersave"
governor, hence never "unleashing the beast". This was a performance
issue.
=> [Tone] Enable bus accounting and memory latency control

rootdir/init.tone.pwr.rc
This scales the minimum CPU bandwidth monitoring based
on CPU frequency dictated by cpufreq API.
This allows for generally better bus scaling.
=> [Tone] Scale min CPU bandwidth device based on cpufreq

PlatformConfig.mk
Use 3 surface buffers for framebuffer and enable
HWC2 platform-wide to take advantage of the
new non-speculative fences performance.
=> [TONE] Use fb triple buffering and enable HWC2

rootdir/init.recovery.tone.rc, rootdir/init.tone.rc
The property sys.usb.controller needs to be set for the OS
to know the actual USB class path, relative to the
controller used by the machine.
=> [k4.4 TONE] Configure standard init and recovery for USB ConfigFS

rootdir/fstab.tone
this partition contains libraries required for proper functionality of the ADSP
=> rootdir: fstab: add /dsp partition mounting

rootdir/ueventd.tone.rc
This is needed for DRS to work.
=> [TONE] ueventd: Add permissions to fb0 node for Dynamic Resolution Switch

rootdir/init.tone.pwr.rc
Change the frequency from 1305600 to 1324800
This prevents the following error message in the kernel log:
cpufreq: invalid target_freq: 1305600
=> Change the interactive hispeed_freq to 1324800

rootdir/init.tone.rc
Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I645d22e899735415cc15c821042c4df3b0f169a4
=> [master] sony: tone: Increase max number of compression streams

rootdir/init.tone.rc
Android can not write fw to the sysfs node due to missing permissions:
E android.hardware.wifi@1.0-service: Failed to open wlan fw path param: Permission denied
By setting the user to wifi, fw can be written and wifi starts properly.
Also, fix a small comment issue where wifi related command was annotated by Bluetooth.
=> rootdir: init: set wifi user for bcmdhd firmware path

rootdir/init.tone.rc
daemon fingerprint is not more on android oreo it was replaced by android.hardware.biometrics.fingerprint
=> tone: remove not needed fingerprint service

rootdir/system/etc/audio_platform_info.xml
based on CAF https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/tree/configs/msm8996/audio_platform_info.xml?h=audio-userspace.lnx.3.0.r2-rel
cleanup unused SND_DEVICES on AudioHAL AOSP
compare these removes from aosp https://android.googlesource.com/platform/hardware/qcom/audio/+/android-8.0.0_r9/hal/msm8974/platform.c
compare these removes from caf  https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/tree/hal/msm8974/platform.c?h=audio-userspace.lnx.3.0.r2-rel
disable USECASE_AUDIO_PLAYBACK_ULL pcm_id which cause pcm_prepare conflicts
=> tone: update audio_platform_info.xml

Android.mk
The filter-out version was not null proof.
In case of PRODUCT_PLATFORM being unset (for example when building a non sony device with Sony trees local) the filter-out condition was falsely turning true and called all sub-makefiles, which is obviously nothing we want.
=> tone: Use standard ifeq in Android.mk

platform.mk, rootdir/system/etc/p2p_supplicant_overlay.conf, rootdir/system/etc/wpa_supplicant_overlay.conf
Since kernel was fixed (bcmdhd driver) this overlay is not necessary.
Change-Id: Iba78f608cf8b76bf5a1d21b4fc0e7c8d6d3fb982
=> [master] sony: tone: Add aosp wpa/p2p overlay back

platform.mk, rootdir/system/etc/p2p_supplicant_overlay.conf, rootdir/system/etc/wpa_supplicant_overlay.conf
Since kernel was fixed (bcmdhd driver) this overlay is not necessary.
Change-Id: Iba78f608cf8b76bf5a1d21b4fc0e7c8d6d3fb982
=> [n-mr1] sony: tone: Add aosp wpa/p2p overlay back

platform.mk
needed for USB tethering usecase
=> tone: add sys.usb.rndis.func.name prop

sepolicy_platform/file_contexts
This is used by the common rdclean.sh rules, see device/sony/common
for the details.
Signed-off-by: Oleksiy Avramchenko <oleksiy.avramchenko@sony.com>
=> tone: label ramdump partition

rootdir/ueventd.tone.rc
Add /dev/fingerprint perms for the new IOCTL implementation.
=> [TONE] ueventd: Fix for FPC IOCTL implementation

sepolicy_platform/genfs_contexts
following commit https://github.com/sonyxperiadev/device-sony-yoshino/commit/e86a6328c063e1fba04a61490eed732838574269#diff-4fc6aac355aec173fea596908e6691d2
=> tone: add AOSP's concept of hardware specific genfs contexts

sepolicy_platform/file_contexts
We use the oem partition to store vendor blobs and we mark the
partition as system_block_device
Signed-off-by: Alin Jerpelea <alin.jerpelea@sonymobile.com>
=> sepolicy: add oem partition

sepolicy_platform/file_contexts
We use the oem partition to store vendor blobs and we mark the
partition as system_block_device
Signed-off-by: Alin Jerpelea <alin.jerpelea@sonymobile.com>
=> [N-MR1] sepolicy: add oem partition

rootdir/init.tone.rc
There is a symlink from /vendor to /system/vendor.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> tone: Fix service path for Android O

rootdir/system/etc/audio_platform_info.xml
ACDB configuration not correctly loaded for SND_DEVICE_IN_HEADSET_MIC
due to spelling mistake.
There are more issues than this to fix VOIP but this is part of it
=> SND_DEVICE_IN_HEADSET_MIC spelling mistake correction

rootdir/fstab.tone
After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.
=> [master] fix generation of OTA packages

rootdir/fstab.tone
After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.
=> [o-mr0] fix generation of OTA packages

rootdir/vendor/etc/init/init.tone.rc
MSM8996 has 2+2 power/perf cluster configuration, so the affinity
should be '3' (corresponds to 0011 binary CPU mask)
=> Fix the default IRQ affinity to the primary cluster.

rootdir/vendor/etc/init/init.tone.pwr.rc
Current configuration is a mix of CAF tuning for msm8956 and msm8998, that have >=6  cores (unlike msm8996 with its 4 cores) what leads to poor performance on this platform. This patchset (except last commit) resets scheduler configuration to CAF one. Even though it is not perfect, it's still better than previous both performance- and battery-wise.
Reference for CAF settings: https://source.codeaurora.org/quic/la/device/qcom/common/tree/rootdir/etc/init.qcom.post_boot.sh?h=LA.UM.6.5.r1-07400-8x96.0
=> Update HMP configuration for tone platform

sepolicy_platform/genfs_contexts
10-10 12:24:33.456  1171  1171 I android.hardwar: type=1400 audit(0.0:66): avc: denied { open } for path=/sys/devices/platform/soc/900000.qcom,mdss_mdp/caps dev=sysfs ino=36085 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
10-10 12:24:33.456  1171  1171 I android.hardwar: type=1400 audit(0.0:67): avc: denied { getattr } for path=/sys/devices/platform/soc/900000.qcom,mdss_mdp/caps dev=sysfs ino=36085 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
10-10 12:24:43.337  1289  1289 I android.hardwar: type=1400 audit(0.0:73): avc: denied { read } for name=caps dev=sysfs ino=36085 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1 …
=> sepolicy: add selinux for kernel 4.9

rootdir/vendor/etc/rqbalance_config.xml
Add the configuration for the sustained performance power hint,
plus limit the cluster frequencies for the batterysave mode.
=> [TONE] rqbalance_config: Add sustained performance and extend batterysave

rootdir/vendor/usr/idc/clearpad.idc
Changes introduced in Android 8.1.0 produced a miscalculation
of the touch pressure axis.
Change the touch pressure scale to 0.01 to prevent overflowing
and get back the touch pressure working properly, solving issues
with multi-touch gestures in various games.
Also, while at it, make sure that the device is declared as internal,
orientation aware and that the touch pressure parameter is read
from the "pressure axis" sent by the kernel driver.
=> [TONE] vendor: IDC: clearpad: Fix touch pressure issues and cleanup

PlatformConfig.mk
=> Allow overriding TARGET_RECOVERY_FSTAB

rootdir/vendor/etc/fstab.tone
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] fstab: Update paths for k4.9

sepolicy_platform/genfs_contexts
09-07 10:50:13.090   549   549 I healthd : type=1400 audit(0.0:150): avc: denied { open } for path=/sys/devices/platform/soc/400f000.qcom,spmi/spmi-0/spmi0-02/400f000.qcom,spmi:pmi8994@2:qcom,qpnp-smbcharger/power_supply/battery/present dev=sysfs ino=42733 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
09-07 10:50:13.090   549   549 I healthd : type=1400 audit(0.0:151): avc: denied { getattr } for path=/sys/devices/platform/soc/400f000.qcom,spmi/spmi-0/spmi0-02/400f000.qcom,spmi:pmi8994@2:qcom,qpnp-smbcharger/power_supply/battery/present dev=sysfs ino=42733 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
=> label battery/present needed by healthd

sepolicy_platform/genfs_contexts
05-02 08:14:06.950   549   549 I healthd : type=1400 audit(0.0:4): avc: denied { open } for path=/sys/devices/platform/soc/400f000.qcom,spmi/spmi-0/spmi0-02/400f000.qcom,spmi:pmi8994@2:bcl@4200/power_supply/fg_adc/type dev=sysfs ino=43124 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
05-02 08:14:06.950   549   549 I healthd : type=1400 audit(0.0:5): avc: denied { getattr } for path=/sys/devices/platform/soc/400f000.qcom,spmi/spmi-0/spmi0-02/400f000.qcom,spmi:pmi8994@2:bcl@4200/power_supply/fg_adc/type dev=sysfs ino=43124 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
=> label bcl as sysfs_batteryinfo

PlatformConfig.mk
brcmfmac uses the kernel's firmware API to get what it needs.
Do not declare any fw paths in that case to avoid wifi hal failure.
Cherry-picked from https://github.com/sonyxperiadev/device-sony-loire/pull/227
=> [TONE] PlatformConfig: declare fw paths only if brcmfmac is not used

platform.mk, rootdir/vendor/etc/init/init.tone.rc, rootdir/vendor/ueventd.rc, sepolicy_platform/genfs_contexts
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
This branch for Android P+ and it uses kernel 4.9 only.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] Remove deprecated paths

rootdir/vendor/ueventd.rc
Last two commits broke leds on kagura.
Will trim this down and squash.
=> [Ready for merge] Restore LED path conditions

PlatformConfig.mk
This platform uses old Adreno binaries and is not compatible
with the new style gralloc.
=> [TONE] PlatformConfig: Define TARGET_USES_GRALLOC1 for legacy

sepolicy_platform/genfs_contexts
This is needed because the `charger` and `healthd` services will try to access it.
`sysfs_batteryinfo` should be strict enough.
=> Add sepolicy context to type-c power_supply

sepolicy_platform/genfs_contexts
Move the definition to common for all platforms. It is the same anyway(except for tama, which doesn't have it).
Has to do with my wish to convert it to `sysfs_bus_esoc`, see https://github.com/sonyxperiadev/device-sony-sepolicy/compare/master...ix5:broad-updates?expand=1#diff-b853b8c814752e09883fb398afe7d1a0R68
Happy to discuss
=> Move /sys/bus/esoc label to common sepolicy

rootdir/vendor/etc/fstab.tone
The /system/vendor/dsp mountpoint follows the other legacy platforms.
Add qdsp_device selinux context for early init processing and set to read-only directly.
Before, we were mounting /dsp read-write, running restorecon_recursive from init.common.rc and then re-mounting read-only.
This is needed since restorecon does not work properly on symlinked /vendor directories.
=> Move dsp mount to /system/vendor, add SELinux contexts, mount read-only early

PlatformConfig.mk
Rename BOARD_SEPOLICY_DIRS to BOARD_VENDOR_SEPOLICY_DIRS
for the vendor/ subfolder.
This is needed for split sepolicy compatibility.
See system/sepolicy/Android.mk:
> BOARD_SEPOLICY_DIRS was used for vendor/odm sepolicy customization before.
> It has been replaced by BOARD_VENDOR_SEPOLICY_DIRS (mandatory) and
> BOARD_ODM_SEPOLICY_DIRS (optional). BOARD_SEPOLICY_DIRS is still allowed for
> backward compatibility, which will be merged into BOARD_VENDOR_SEPOLICY_DIRS.
ifdef BOARD_SEPOLICY_DIRS
BOARD_VENDOR_SEPOLICY_DIRS += $(BOARD_SEPOLICY_DIRS)
endif
=> [tone] Board sepolicy: Fix legacy build variable

sepolicy_platform/genfs_contexts
Needed to set correct restart levels.
=> sepolicy_platform: Label kgsl-hyp subsystem

rootdir/vendor/etc/fstab.tone
Since there is no longer a command in init.common.rc that remounts as read-only, set the property directly in fstab.
=> [tone] fstab: Mount dsp partition read-only

rootdir/vendor/etc/audio_platform_info.xml
The entry for this calibration seems to be badly read or
corrupted: that makes it the kernel to send a Q6 CVP
parameter that is setting 15 RX channels and that is
obviously ... wrong.
Disable the ACDB calibration for the BT SCO WB device
at least until the database gets eventually fixed.
This PR fixes in-call BT audio
=> [TONE] audio_platform_info: Disable ACDB for OUT_BT_SCO_WB

rootdir/vendor/etc/rqbalance_config.xml
This platform is very weak: two CPUs aren't going to make the
day at all.
Allow more computational power on the balanced profile and be
less restrictive on the powersave one, where the device would
be too slow to be usable with just a single core.
=> [TONE] rqbalance: Allow more computational power

platform.mk
Set primary mixer stages to 1 to force getting no blend
support from the display HAL.
This switches us from the SDE composition to the GPU
composition, which is a hack that is required for legacy
platforms on the SDE driver because of a severe
incompatibility with the current blobs.
There are no barriers because the FBDEV driver-HAL
combo have no blobs to support the SDM composition
and this configuration is anyway already doing what we
are forcing there.
=> [TONE] platform: Disable SDE composition by forcing no blend

PlatformConfig.mk
bcmdhd implementation relies on custom ioctls that are not supported by the mainline brcmfmac driver.
qcwcn libs is closer to the standard interfaces, and hence actually more compatible than bcmdhd libs.
also remove the declaration of firmware paths if bcmdhd is used, since it is now compeletely superceded by brcmfmac and will not be considered again.
=> PlatformConfig: switch wifi libs to qcwcn from bcmdhd

platform.mk
Loading the extension library fails because it can not find libscalar.so, which is indeed not provided.
This leads to failure when initializing the display hal.
Since the extension interface is not critically required on tone while still not switched to DRM, skip it.
This commit MUST be reverted after switching to DRM, because then the extension interface is critical for clocks managment.
=> [TEMP] platform: add property to skip loading libsdmextension

sepolicy_platform/genfs_contexts
04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:21): avc: denied { read } for name=address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:22): avc: denied { open } for path=/sys/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/net/wlan0/address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:23): avc: denied { getattr } for path=/sys/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/net/wlan0/address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 …
=> sepolicy: label brcmfmac mac_adress 1/2

platform.mk, rootdir/vendor/libnfc-nci.conf
All tone devices share the `PN547C2` chip and the NCI config can be unified.
This change also moves the files from /system/etc to /vendor/etc for treble compliance. Since `nfc` is a system service, this means the `libnfc-nci.conf` file in `/vendor` needs to be labeled in sepolicy and the `nfc` domain needs to be granted access.
keyaki did not previously force tag polling, this commit also brings it in line with the other tone devices by integrating this commit from kagura/dora:
> Force tag polling for all available technologies
>
> Bring back the POLLING_TECH_MASK config entry and set it to force tag polling for all available techs.
>
> Without this config the chip will not work properly.
>
> Signed-off-by: Humberto Borba <humberos@omnirom.org>
> Change-Id: …
=> [WIP] Move libnfc-nci.conf to tone shared

sepolicy_platform/genfs_contexts
Needed for the health HAL to extract storage health and statistics.
See https://github.com/sonyxperiadev/device-sony-common/pull/628 and https://github.com/sonyxperiadev/device-sony-sepolicy/pull/530
=> [WIP] sepolicy_platform: Label sdhci MMC node

rootdir/vendor/etc/init/init.tone.rc
Limit MTP_RX_BUFFER_INIT_SIZE and MTP_TX_BUFFER_INIT_SIZE from 1048576 to 16384
Should fix swiotlb running OOM with large file transfers.
See https://github.com/sonyxperiadev/bug_tracker/issues/432#issuecomment-517964636
Needs accompanying sepolicy.
=> [VERIFYME] init: Limit MTP rx/tx buffers to 16384

rootdir/vendor/etc/audio_platform_info.xml
For https://github.com/sonyxperiadev/bug_tracker/issues/509
Much like OUT_BT_SCO_WB, the acdb entry for OUT_BT_SCO contains a bogus
number of TX channels that break in the DSP, leading to no audio in
voice calls. Disabling this calibration gives an appropriate and working
default configuration.
While not being confirmed that the _TX_ channels (not RX) were exactly
15, they were something other than 1; the reporter confirmed that
forcing this value back to 1 (exactly how the _WB issue was initially
solved: https://sx.ix5.org/info/post/bluetooth-audio-debugging/ fixes
the issue here as well).
For completeness, see the commit message from the OUT_BT_SCO_WB
disablement:
> The entry for this calibration seems to be badly read or
> corrupted: that makes it the kernel to send a Q6 CVP
> …
=> audio_platform_info: Disable ACDB for OUT_BT_SCO

platform.mk, rootdir/vendor/etc/audio_policy_configuration.xml, rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml, rootdir/vendor/etc/common_primary_audio_policy_configuration.xml
The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.
=> [TONE] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

platform.mk
The config-bcm.mk makefile in hardware/broadcom/wlan will potentially overwrite our own configs.
Handle a nonexistent repo gracefully by using `inherit-product-if-exists`.
=> platform: Relax inheritance on broadcom wlan repo
